// components/Header.tsx
import React from "react";
import Link from "next/link";
import Styles from "/pages/page.module.css";

interface HeaderProps {
  searchTerm: string;
  setSearchTerm: React.Dispatch<React.SetStateAction<string>>;
}

const Header: React.FC<HeaderProps> = ({ searchTerm, setSearchTerm }) => {
  return (
    <div>
      <p className="text-xs">Generated by SRF</p>
      <nav className="flex justify-between">
        <h1 className="text-md md:text-xl">Sooriya Publishers</h1>
        <ul className="flex items-center">
          {/* Search Bar */}
          <input
            type="search"
            placeholder="Search for books..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="border-2 border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50 rounded-md shadow-sm"
          />
          
          <li>
            <Link href="/" className={Styles.link}>
             Home
            </Link>
          </li>
          {/* Add other navigation links as needed */}
          <li className="mx-1">
              <Link href="/Religion/page" className={Styles.link}>
                Religion
              </Link>
            </li>
            <li className="mx-1">
              <Link href="/History/page" className={Styles.link}>
                History
              </Link>
            </li>
            <li className="mx-1">
              <Link href="/Politics/page" className={Styles.link}>
                Politics
              </Link>
            </li>
            <li className="mx-1">
              <Link href="/Science/page" className={Styles.link}>
                Science
              </Link>
            </li>
            <li className="mx-1">
              <Link href="/Economy/page" className={Styles.link}>
                Economy
              </Link>
            </li>
            <li>
              <Link href="/Other/page" className={Styles.link}>
                Other
              </Link>
            </li>
        </ul>
      </nav>
    </div>
  );
};

export default Header;
