// components/Header.tsx
import React from "react";
import Link from "next/link";
import Styles from "/pages/page.module.css";
import { Input } from '@mantine/core';

interface HeaderProps {
  searchTerm: string;
  setSearchTerm: React.Dispatch<React.SetStateAction<string>>;
}

const Header: React.FC<HeaderProps> = ({ searchTerm, setSearchTerm }) => {
  return (
    <div>
      <p className="text-xs">Generated by SRF</p>
      <nav className="flex justify-between items-center">
        <h1 className="text-md md:text-xl">Sooriya Publishers</h1>
        <ul className="flex items-center gap-1">

          {/* Search Bar */}
          <li className="relative">
          <input
            type="search"
            placeholder="Search for books..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
           style={{
             border: "2px solid #ccc",
             borderRadius: "4px",
          }}
          />
          </li>
          
          <li>
            <Link href="/" className={Styles.link}>
             Home
            </Link>
          </li>
          {/* Add other navigation links as needed */}
          <li>
              <Link href="/Religion/page" className={Styles.link}>
                Religion
              </Link>
            </li>
            <li>
              <Link href="/History/page" className={Styles.link}>
                History
              </Link>
            </li>
            <li>
              <Link href="/Politics/page" className={Styles.link}>
                Politics
              </Link>
            </li>
            <li>
              <Link href="/Science/page" className={Styles.link}>
                Science
              </Link>
            </li>
            <li>
              <Link href="/Economy/page" className={Styles.link}>
                Economy
              </Link>
            </li>
            <li>
              <Link href="/Other/page" className={Styles.link}>
                Other
              </Link>
            </li>
        </ul>
      </nav>
    </div>
  );
};

export default Header;
